// User constants for managing user data
export const ADMIN_USER_LIST_REQ = "ADMIN_USER_LIST_REQ";
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS";
export const ADMIN_USER_LIST_FAIL = "ADMIN_USER_LIST_FAIL";

export const ADMIN_USER_DETAIL_REQ = "ADMIN_USER_DETAIL_REQ";
export const ADMIN_USER_DETAIL_SUCCESS = "ADMIN_USER_DETAIL_SUCCESS";
export const ADMIN_USER_DETAIL_FAIL = "ADMIN_USER_DETAIL_FAIL";

export const ADMIN_USER_UPDATE_REQ = "ADMIN_USER_UPDATE_REQ";
export const ADMIN_USER_UPDATE_SUCCESS = "ADMIN_USER_UPDATE_SUCCESS";
export const ADMIN_USER_UPDATE_FAIL = "ADMIN_USER_UPDATE_FAIL";

export const ADMIN_USER_DELETE_REQ = "ADMIN_USER_DELETE_REQ";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAIL = "ADMIN_USER_DELETE_FAIL";

export const ADMIN_USER_ADD_REQ = "ADMIN_USER_ADD_REQ";
export const ADMIN_USER_ADD_SUCCESS = "ADMIN_USER_ADD_SUCCESS";
export const ADMIN_USER_ADD_FAIL = "ADMIN_USER_ADD_FAIL";