export const GIFT_CARD_REQ = "GIFT_CARD_REQ";
export const GIFT_CARD_SUCCESS = "GIFT_CARD_SUCCESS";
export const GIFT_CARD_FAIL = "GIFT_CARD_FAIL";

export const GIFT_CARD_REDEEM_REQ = "GIFT_CARD_REDEEM_REQ";
export const GIFT_CARD_REDEEM_SUCCESS = "GIFT_CARD_REDEEM_SUCCESS";
export const GIFT_CARD_REDEEM_FAIL = "GIFT_CARD_REDEEM_FAIL";

export const GIFT_CARD_BALANCE_REQ = "GIFT_CARD_BALANCE_REQ";
export const GIFT_CARD_BALANCE_SUCCESS = "GIFT_CARD_BALANCE_SUCCESS";
export const GIFT_CARD_BALANCE_FAIL = "GIFT_CARD_BALANCE_FAIL";
