export const GIFT_CARD_CHECK_BALANCE_REQUEST = 'GIFT_CARD_CHECK_BALANCE_REQUEST';
export const GIFT_CARD_CHECK_BALANCE_SUCCESS = 'GIFT_CARD_CHECK_BALANCE_SUCCESS';
export const GIFT_CARD_CHECK_BALANCE_FAIL = 'GIFT_CARD_CHECK_BALANCE_FAIL';
export const GIFT_CARD_RESET_BALANCE = 'GIFT_CARD_RESET_BALANCE';

export const GIFT_CARD_USE_REQUEST = 'GIFT_CARD_USE_REQUEST';
export const GIFT_CARD_USE_SUCCESS = 'GIFT_CARD_USE_SUCCESS';
export const GIFT_CARD_USE_FAIL = 'GIFT_CARD_USE_FAIL';

export const ADMIN_GIFT_CARD_LIST_REQUEST = 'ADMIN_GIFT_CARD_LIST_REQUEST';
export const ADMIN_GIFT_CARD_LIST_SUCCESS = 'ADMIN_GIFT_CARD_LIST_SUCCESS';
export const ADMIN_GIFT_CARD_LIST_FAIL = 'ADMIN_GIFT_CARD_LIST_FAIL';

export const ADMIN_GIFT_CARD_CREATE_REQUEST = 'ADMIN_GIFT_CARD_CREATE_REQUEST';
export const ADMIN_GIFT_CARD_CREATE_SUCCESS = 'ADMIN_GIFT_CARD_CREATE_SUCCESS';
export const ADMIN_GIFT_CARD_CREATE_FAIL = 'ADMIN_GIFT_CARD_CREATE_FAIL';

export const ADMIN_GIFT_CARD_DELETE_REQUEST = 'ADMIN_GIFT_CARD_DELETE_REQUEST';
export const ADMIN_GIFT_CARD_DELETE_SUCCESS = 'ADMIN_GIFT_CARD_DELETE_SUCCESS';
export const ADMIN_GIFT_CARD_DELETE_FAIL = 'ADMIN_GIFT_CARD_DELETE_FAIL';

export const ADMIN_GIFT_CARD_UPDATE_BALANCE_REQUEST = 'ADMIN_GIFT_CARD_UPDATE_BALANCE_REQUEST';
export const ADMIN_GIFT_CARD_UPDATE_BALANCE_SUCCESS = 'ADMIN_GIFT_CARD_UPDATE_BALANCE_SUCCESS';
export const ADMIN_GIFT_CARD_UPDATE_BALANCE_FAIL = 'ADMIN_GIFT_CARD_UPDATE_BALANCE_FAIL';

export const CLEAR_GIFT_CARD_SUCCESS = 'CLEAR_GIFT_CARD_SUCCESS';
