export const ORDER_REQ = "ORDER_REQ"
export const ORDER_RESET = "ORDER_RESET"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_FAIL = "ORDER_FAIL"

export const ORDER_PAYMENT_REQ = "ORDER_PAYMENT_REQ"
export const ORDER_PAYMENT_REQ_FAIL = "ORDER_PAYMENT_REQ_FAIL"
export const ORDER_PAYMENT_REQ_SUCCESS = "ORDER_PAYMENT_REQ_SUCCESS"

export const ORDER_DETAIL_REQ = "ORDER_DETAIL_REQ"
export const ORDER_DETAIL_REQ_FAIL = "ORDER_DETAIL_REQ_FAIL"
export const ORDER_DETAIL_REQ_SUCCESS = "ORDER_DETAIL_REQ_SUCCESS"

export const ORDER_LIST_REQ = "ORDER_LIST_REQ"
export const ORDER_LIST_REQ_FAIL = "ORDER_LIST_REQ_FAIL"
export const ORDER_LIST_REQ_SUCCESS = "ORDER_LIST_REQ_SUCCESS"

// ADMIN TINGS
export const ORDER_DELIVERY_REQ = "ORDER_DELIVERY_REQ";
export const ORDER_DELIVERY_SUCCESS = "ORDER_DELIVERY_SUCCESS";
export const ORDER_DELIVERY_FAIL = "ORDER_DELIVERY_FAIL";

export const ADMIN_ORDER_LIST_REQ = 'ADMIN_ORDER_LIST_REQ';
export const ADMIN_ORDER_LIST_SUCCESS = 'ADMIN_ORDER_LIST_SUCCESS';
export const ADMIN_ORDER_LIST_FAIL = 'ADMIN_ORDER_LIST_FAIL';





