export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ"
export const PRODUCT_LIST_REQ_SUCCESS = "PRODUCT_LIST_REQ_SUCCESS"
export const PRODUCT_LIST_REQ_FAIL = "PRODUCT_LIST_REQ_FAIL"

export const PRODUCT_DETAIL_REQ = "PRODUCT_DETAIL_REQ"
export const PRODUCT_DETAIL_REQ_SUCCESS = "PRODUCT_DETAIL_REQ_SUCCESS"
export const PRODUCT_DETAIL_REQ_FAIL = "PRODUCT_DETAIL_REQ_FAIL"

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
